### ISSUE TITLE
Document QUETZ_GITHUB_CLIENT_ID and delete the setup_env?

### ISSUE THREAD

**Issue by wolfv** [TheSnakePit/quetz#1]
Just in case, before we go public, we should probably erase the setup_env.sh :)

**Comment by mariobuikhuizen** [comment]
That only gives access to localhost, and lets the application work out of the box. I couldn't think of security risk in this setup, but if there is, we should remove it. I have since renamed the file to setup_env_dev to make that a bit more clear.

**Comment by wolfv** [comment]
Ok, if you thought about this then I guess it's fine :)
