### ISSUE TITLE
Parse config from a file

### ISSUE THREAD

**Issue by benjamb** [TheSnakePit/quetz#25]
Is there are preferred format (yaml, json, ini, toml)?

While this could perhaps be a separate issue, it would also be nice to be able to have configs parsed as command line options (configargparse would be good for this).

uvicorn could then be run programmatically, with the port/listen address (and other settings) loaded from the config.

**Comment by wolfv** [comment]
definitely a good idea! 

From my perspective, I would use either yaml (as it is used a lot in the conda ecosystem) or TOML (as I think it's very clean and easy to write by hand).
ConfigArgParse looks good to me (haven't used it before).

There are a bunch of argparse alternatives for Python that might support config files out of the box as well, but I am fine with your choice.
