### ISSUE TITLE
Support for S3

### ISSUE THREAD

**Issue by benjamb** [TheSnakePit/quetz#6]
It's great to see an open-source Conda/Mamba package repository, definitely a step in the right direction.

It would be great if Quetz were to use the S3 API to store objects. Aside from the ease of scaling horizontally it would provide, we could:

* Use object locking to avoid unwanted side-effects from simultaneous uploads (e.g. race conditions during indexing);
* Defer writes to disk (indexing aside), relying on the durability and reliability of S3;

Would you be open to a contribution implementing support for this?

**Comment by wolfv** [comment]
Hi @benjamb 

thanks for dropping by! Yes, I would be very excited to see this, and a condition would be very much appreciated. 

I am wondering if we could re-use a library such as PyFilesystem (https://www.pyfilesystem.org/page/index-of-filesystems/) for this. I haven't used PyFilesystem before, and I am not sure if it's performant & flexible enough but a layer of abstraction between the filesystem and the implementation seems nice.

But we could probably implement that sort of abstractions ourselves, anyways. Let us know what you think.

**Comment by davidbrochart** [comment]
Might be worth looking at too: https://filesystem-spec.readthedocs.io

**Comment by benjamb** [comment]
@wolfv Yeah, I think PyFilesystem could be a good way to do it. I do wonder whether there will be much overhead over directly using boto3, but perhaps that will be negligible.

**Comment by xhochy** [comment]
I would be interesting in adding support for GCS but would actually prefer using https://filesystem-spec.readthedocs.io as a general abstraction layer as that is currently getting currently quite some active development with focus on speed / minimal overhead. (Arrow also provides an interface in the next release to use these filesystems from C++).

**Comment by wolfv** [comment]
Indeed, filesystem-spec looks really good. @benjamb do you want to give it a shot?

**Comment by dhirschfeld** [comment]
I'd like to use it with Azure Blob/Files Storage so using `fsspec` would be good as it should allow for this as well.

**Comment by benjamb** [comment]
@wolfv I do indeed. I have already been experimenting with `fsspec`.

**Comment by wolfv** [comment]
cool, let us know how it goes!

**Comment by benjamb** [comment]
A bit of an update on this:
I have done some work on this and fsspec/s3fs for the most part seems great. Have bucket creation in place, and thus requests to upload and download files are then be routed to the appropriate S3 bucket. Unfortunately indexing has been a bit of a problem.

At present, Quetz makes a call to `conda index` against a specific channel when finalising a package upload request to generate the relevant package index metadata, though this currently does not support S3 as a backend. I had read that some members of the community had some success in running `conda index` against a FUSE based s3 filesystem, and while I didn't think that would be suitable in the long-term, it would have been good enough to start with. However I've experienced inconsistencies and flakiness which have proven difficult to debug, which I've decided aren't putting more time into.

As such we've had a few thoughts on how we could improve indexing, I won't go into too much detail here though. Though by storing further package metadata within the database, it would allow us to generate (and thus cache) index metadata on the fly.

**Comment by wolfv** [comment]
Thanks @benjamb for the update.
Indeed, I think the call to `conda index` should be thought of as only a stopgap solution.
If we really want to implement fine-grained permissions, this also means that we have to serve different repodata.json files based on permission. So we will have to generate (and cache) repodata.json from the database rather than the folder.

I personally think that we should store some metadata in the database, but we should probably also unpack the `/info/...` files from the package and store them somewhere (extracted) and accessible.

E.g. I think it would be interesting to be able to access the info files by going to `/api/packages/my-pkg-123/info/index.json`.

Just to avoid duplicating work -- do you think you guys are going to continue working on these problems? Do you think we should sync at some point?

**Comment by nowster** [comment]
@wolfv  I'm currently working on exactly that problem: storing repodata/channeldata info into the database.

**Comment by wolfv** [comment]
As far as I can tell we have S3 support now! So I am going to close this issue (thanks @nowster !)
